### PR TITLE
Removed new object creation from onBind method of class NewsViewHolder

### PR DESCRIPTION
**Pull request by sanjeevyadavIT**
DESCRIPTION : Avoid creating new object reference in onBindViewHolder function, because the way recycler view works, onBindViewHolder is call each time when user scroll and every time instance of SimpleDateFormat and OnCLickListener is created.

Made NewsViewHolder inner class of NewsAdapter to setup OnClick listener for RecyclerView item correctly, which optimizes and less object are created.

### CODE REVIEW

**Comment by sanjeevyadavIT** [comment]
PS : That is the cleanest code I have seen in my life, it was clear and readable, from where did you learn to write clean code, any book?

**Comment by s-buvaka** [comment]
> PS : That is the cleanest code I have seen in my life, it was clear and readable, from where did you learn to write clean code, any book?

O_o. Oh thanks. I have a good teacher. I read "Perfect McConnell Steve Code"?https://www.ozon.ru/context/detail/id/3159814/

**Comment by s-buvaka** [comment]
> DESCRIPTION : Avoid creating new object reference in onBindViewHolder function, because the way recycler view works, onBindViewHolder is call each time when user scroll and every time instance of SimpleDateFormat and OnCLickListener is created.
> 
> Made NewsViewHolder inner class of NewsAdapter to setup OnClick listener for RecyclerView item correctly, which optimizes and less object are created.

And yes, thanks for the advice. I'll take it into account.

**Comment by sanjeevyadavIT** [comment]
Can you tell me more about this project, what is it that you are making, your goal and is there any way i can contribute?

**Comment by sanjeevyadavIT** [comment]
Hello I was just going through the code, in `NewsListActivty.java`, you have wriiten this code
    `

    protected void onDestroy() {
        super.onDestroy();
        newsAdapter = null;
        newsRecycler = null;
        progress = null;
        disposable.dispose();
        disposable = null;
    }`

why have you wriiten this line `newsRecycler = null;` is there any specific reason that you have written recycler view to be null in onDestroy, doesn't Garbage collector will handle it automatically????

**Comment by s-buvaka** [comment]
This link is referenced by the context of the activity. If I do not
unsubscribe from the link, then I get a memory leak.

1 нояб. 2018 г. 1:44 ДП пользователь "Sanjeev yadav" <
notifications@github.com> написал:

Hello I was just going through the code, in NewsListActivty.java, you have
wriiten this code
`

protected void onDestroy() {
    super.onDestroy();
    newsAdapter = null;
    newsRecycler = null;
    progress = null;
    disposable.dispose();
    disposable = null;
}`

why have you wriiten this line newsRecycler = null; is there any specific
reason that you have written recycler view to be null in onDestroy, doesn't
Garbage collector will handle it automatically????

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/industradamus/BusinessCard/pull/5#issuecomment-434873085>,
or mute the thread

**Pull request closed without merging**
